In [3]:
import pandas as pd
import seaborn as sns
import numpy as np

In [4]:
df = sns.load_dataset('Iris')

In [5]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [7]:
X= df.iloc[:,0:4]

In [8]:
Y= df.iloc[:,-1]

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.2)

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
scaler= StandardScaler()

In [13]:
x_train=pd.DataFrame(scaler.fit_transform(x_train))

In [14]:
x_test=scaler.transform(x_test)

In [15]:
round(x_train.describe(),1)

0      1      2      3
count  120.0  120.0  120.0  120.0
mean    -0.0   -0.0   -0.0    0.0
std      1.0    1.0    1.0    1.0
min     -1.8   -2.5   -1.5   -1.5
25%     -1.0   -0.6   -1.3   -1.1
50%     -0.1   -0.1    0.3    0.2
75%      0.6    0.6    0.7    0.7
max      2.4    3.2    1.8    1.7

In [16]:
from sklearn.naive_bayes import GaussianNB

In [17]:
mdl = GaussianNB()

In [18]:
mdl.fit(x_train, y_train)

GaussianNB()

In [19]:
y_pred=mdl.predict(x_test)

In [20]:
y_pred

array(['virginica', 'virginica', 'setosa', 'versicolor', 'virginica',
       'versicolor', 'setosa', 'virginica', 'setosa', 'virginica',
       'setosa', 'setosa', 'virginica', 'setosa', 'versicolor',
       'virginica', 'setosa', 'virginica', 'setosa', 'versicolor',
       'versicolor', 'setosa', 'versicolor', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'setosa', 'setosa', 'versicolor'],
      dtype='<U10')

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [22]:
accuracy_score(y_pred, y_test)

0.9666666666666667

In [23]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

# Accuracy
acc = accuracy_score(y_test, y_pred)
print("\nAccuracy:", acc)

# Error Rate
error_rate = 1 - acc
print("Error Rate:", error_rate)

# Classification report for Precision, Recall, etc.
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Confusion Matrix:
 [[12  0  0]
 [ 0  9  1]
 [ 0  0  8]]

Accuracy: 0.9666666666666667
Error Rate: 0.033333333333333326

Classification Report:
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        12
  versicolor       1.00      0.90      0.95        10
   virginica       0.89      1.00      0.94         8

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



In [53]:
ar=df['species'].unique()

In [47]:
names=list(df.value_counts('species').index)

In [55]:
for i in range(len(ar)):
   
    TP = cm[i, i]
    FP = cm[:, i].sum() - TP
    FN = cm[i, :].sum() - TP
    TN = cm.sum() - (TP + FP + FN)

    print(f"\nClass: {ar[i]}")
    print(f"TP: {TP}")
    print(f"FP: {FP}")
    print(f"FN: {FN}")
    print(f"TN: {TN}")


SyntaxError: incomplete input (4265211627.py, line 1)

In [49]:
for i, class_name in enumerate(names):
    TP = cm[i, i]
    FP = cm[:, i].sum() - TP
    FN = cm[i, :].sum() - TP
    TN = cm.sum() - (TP + FP + FN)

    print(f"\nClass: {class_name}")
    print(f"TP: {TP}")
    print(f"FP: {FP}")
    print(f"FN: {FN}")
    print(f"TN: {TN}")


Class: setosa
TP: 12
FP: 0
FN: 0
TN: 18

Class: versicolor
TP: 9
FP: 0
FN: 1
TN: 20

Class: virginica
TP: 8
FP: 1
FN: 0
TN: 21
